# Netlify Configuration File
# This fixes the routing issue for Single Page Applications (SPA)
# It redirects all routes to index.html so React Router can handle them

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Headers per millorar seguretat i rendiment
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control per assets estàtics
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"